config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => 'localhost:3000'
  devise_for :users
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :dashboard, only: :index

  resources :programs do
    resource :users
  end

  resource :student_profiles
  resource :employer_profiles
  resource :admin_profiles

end

app/models/admin_profile.rb
class AdminProfile < ApplicationRecord

  has_one :user, as: :profile, dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employer_profile.rb
class EmployerProfile < ApplicationRecord

  has_one :user, as: :profile, dependent: :destroy

end

app/models/program.rb
class Program < ApplicationRecord

  validates :title,
            :start_date,
            :end_date,
            presence: true

end

app/models/student_profile.rb
class StudentProfile < ApplicationRecord

  has_one :user, as: :profile, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  belongs_to :profile, polymorphic: true

  validates :email, presence: true, uniqueness: { case_sensitive: false }

end

app/controllers/admin_controller.rb
class AdminController < BaseController

  layout 'admin_dashboard'

  before_action :require_admin_authorization!
  
end

app/controllers/admin_profiles_controller.rb
class AdminProfilesController < ApplicationController

  def new

  end

  def create

  end

  def edit

  end

  def update

  end

  def destroy

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    dashboard_index_path
  end

end

app/controllers/base_controller.rb
class BaseController < ApplicationController

  before_action :authenticate_user!

  def current_user_profile_type
    current_user.profile_type.underscore
  end

  def require_admin_authorization!
    redirect_to root_url unless current_user.profile_type == 'AdminProfile'
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < BaseController

  layout :get_current_user_layout

  def index
    render "#{current_user_profile_type}"
  end

  private

  def get_current_user_layout
    user_layouts = user_layouts_as_hash
    user_layouts[current_user_profile_type.to_sym]
  end

  def user_layouts_as_hash
    {
      admin_profile: 'admin_dashboard',
      student_profile: 'student_dashboard',
      employer_profile: 'employer_dashboard'
    }
  end

end

app/controllers/programs_controller.rb
class ProgramsController < AdminController

  def new
    @program = Program.new
  end

  def create
    use_case = CreateProgram.call(params: program_params)
    if use_case.success?

      redirect_to programs_url, flash: {success: 'You successfully created program'}
    else
      @program = use_case.program
      render :new
    end
  end

  def show
    @program = Program.find(params[:id])
  end

  def edit
    @program = Program.find(params[:id])
  end

  def update
    @program = Program.find(params[:id])
    use_case = UpdateProgram.call(program: @program, params: program_params)

    if use_case.success?

      redirect_to programs_url, flash: {success: 'You successfully update program'}
    else
      render :edit
    end
  end

  def index
    @programs = Program.all
  end

  def destroy
    @program = Program.find(params[:id])
    DestroyProgram.call(program: @program)

    redirect_to programs_url, flash: {success: 'You successfully destroyed program'}
  end

  private

  def program_params
    params.require(:program).permit(
      :title,
      :start_date,
      :end_date
    )
  end

end

app/controllers/student_profiles_controller.rb
class StudentProfilesController < BaseController

  def new
    @student = StudentProfile.new
  end

  def create

  end

  def edit

  end

  def update

  end

  def destroy

  end

  private

  def student_params

  end

end

app/controllers/users_controller.rb
class UsersController < AdminController

  def new
    @user = User.new
    @program = Program.find(params[:program_id])
    @profile = params[:profile]
    render "#{@profile}"
  end

  def create
    binding.pry
    user_type = params[:user][:user_type]
    use_case = RegisterUser.call(user_type: user_type, params: user_params)

    if use_case.success?

      redirect_to ''
    else


    end
  end

  private

  def user_params
    params.require(:user).permit(
      :email
    )
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admin_profiles_helper.rb
module AdminProfilesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/base_helper.rb
module BaseHelper

  def current_user_name
    current_user.profile.first_name.capitalize + " " + current_user.profile.last_name.capitalize
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employer_profiles_helper.rb
module EmployerProfilesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/student_profiles_helper.rb
module StudentProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/programs/_program_form.html.erb
<%= form_for @program, html: {class: ''} do |f| %>

    <div class="form-row">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="form-row">
      <%= f.label :start_date %>
      <%= f.date_select :start_date  %>
    </div>

    <div class="form-row">
      <%= f.label :end_date %>
      <%= f.date_select :end_date  %>
    </div>

    <div class="form-button">
      <%= f.submit(yield(:create)) %>
    </div>

<% end %>

app/views/programs/edit.html.erb
<% provide(:create, 'Update program') %>
<h6>Update program</h6>
<%= render 'program_form' %>

app/views/programs/index.html.erb
<%= link_to 'new program', new_program_path, class: '' %>

<% if @programs.any? %>
<table class="table table-bordered">

    <tr>
      <th>Title</th>
      <th>State date</th>
      <th>End date</th>
      <th>Actions</th>
    </tr>

  <% @programs.each do |program| %>
    <tr>
      <td><%= link_to program.title, program_path(program), class:'' %></td>
      <td><%= program.start_date.strftime("%B %d, %Y") %></td>
      <td><%= program.end_date.strftime("%B %d, %Y") %></td>
      <td>
        <%= link_to 'edit', edit_program_path(program), class: '' %>
        <%= link_to 'remove', program_path(program), method: :delete, data: {confirm: 'Are you sure?' }, class: '' %>
      </td>
    </tr>
  <% end %>

</table>
<% end %>

app/views/programs/new.html.erb
<% provide(:create, 'Create program') %>
<h6>Create program</h6>
<%= render 'program_form' %>

app/views/programs/show.html.erb
<%= link_to 'register student', new_program_users_path(@program, params: {profile: 'student_profile'}), class: '' %>
<%= link_to 'register employer', new_program_users_path(@program, params: {profile: 'employer_profile'}), class: '' %>
<%= link_to 'register agency', new_program_users_path(@program, params: {profile: 'agent_profile'}), class: '' %>

app/views/student_profiles/new.html.erb
Register a student <br>
<%= link_to 'Register a student' %>

app/views/users/student_profile.erb
<% provide(:register, 'Register') %>
<h6>Register student</h6>

<%= form_for [@program, @user], html: {class: ''} do |f| %>

    <div class="form-row">
      <%= f.hidden_field :profile, value: @profile, class: '' %>
    </div>

    <div class="form-row">
      <%= f.text_field :email, class: '' %>
    </div>

    <div class="form-row">
      <%= f.submit(yield(:register)) %>
    </div>

<% end %>