config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => 'localhost:3000'
  devise_for :users
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :dashboard, only: :index

  resources :programs do
    resource :users
  end

  resource :student_profiles
  resource :employer_profiles
  resource :admin_profiles

end

app/models/admin_profile.rb
class AdminProfile < ApplicationRecord

  has_one :user, as: :profile, dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employer_profile.rb
class EmployerProfile < ApplicationRecord

  has_one :user, as: :profile, dependent: :destroy

end

app/models/program.rb
class Program < ApplicationRecord

  validates :title,
            :start_date,
            :end_date,
            presence: true

end

app/models/student_profile.rb
class StudentProfile < ApplicationRecord

  has_one :user, as: :profile, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  belongs_to :profile, polymorphic: true

  validates :email, presence: true, uniqueness: { case_sensitive: false }

end

app/controllers/admin_controller.rb
class AdminController < BaseController

  layout 'admin_dashboard'

  before_action :require_admin_authorization!
  
end

app/controllers/base_controller.rb
class BaseController < ApplicationController

  before_action :authenticate_user!

  def current_user_profile_type
    current_user.profile_type.underscore
  end

  def require_admin_authorization!
    redirect_to root_url unless current_user.profile_type == 'AdminProfile'
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < BaseController

  layout :get_current_user_layout

  def index
    render "#{current_user_profile_type}"
  end

  private

  def get_current_user_layout
    user_layouts = user_layouts_as_hash
    user_layouts[current_user_profile_type.to_sym]
  end

  def user_layouts_as_hash
    {
      admin_profile: 'admin_dashboard',
      student_profile: 'student_dashboard',
      employer_profile: 'employer_dashboard'
    }
  end

end

app/controllers/programs_controller.rb
class ProgramsController < AdminController

  def new
    @program = Program.new
  end

  def create
    use_case = CreateProgram.call(params: program_params)
    if use_case.success?

      redirect_to programs_url, flash: {success: 'You successfully created program'}
    else
      @program = use_case.program
      render :new
    end
  end

  def show
    @program = Program.find(params[:id])
  end

  def edit
    @program = Program.find(params[:id])
  end

  def update
    @program = Program.find(params[:id])
    use_case = UpdateProgram.call(program: @program, params: program_params)

    if use_case.success?

      redirect_to programs_url, flash: {success: 'You successfully update program'}
    else
      render :edit
    end
  end

  def index
    @programs = Program.all
  end

  def destroy
    @program = Program.find(params[:id])
    DestroyProgram.call(program: @program)

    redirect_to programs_url, flash: {success: 'You successfully destroyed program'}
  end

  private

  def program_params
    params.require(:program).permit(
      :title,
      :start_date,
      :end_date
    )
  end

end

app/controllers/users_controller.rb
class UsersController < AdminController

  def new
    @user = User.new
    @program = Program.find(params[:program_id])
    @profile = params[:profile]
    render "#{@profile}"
  end

  def create
    binding.pry
    user_type = params[:user][:user_type]
    use_case = RegisterUser.call(user_type: user_type, params: user_params)

    if use_case.success?

      redirect_to ''
    else


    end
  end

  private

  def user_params
    params.require(:user).permit(
      :email
    )
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admin_profiles_helper.rb
module AdminProfilesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/base_helper.rb
module BaseHelper

  def current_user_name
    current_user.profile.first_name.capitalize + " " + current_user.profile.last_name.capitalize
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employer_profiles_helper.rb
module EmployerProfilesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/student_profiles_helper.rb
module StudentProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin_dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kenshin</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<div class="header">

  <div class="logo">
    <%= link_to 'Kenshin', root_path, class: 'logo__link' %>
  </div>

  <div class="navigation-links">
    <%= link_to '#', class: 'header__link' do %>
        <span class="fa fa-pie-chart"></span>
        Charts
    <% end %>
    <%= link_to '#', class: 'header__link' do %>
        <span class="fa fa-dashboard"></span>
        Dashboard
    <% end %>
  </div>

  <div class="search">
    <%= form_tag 'some_path' do %>
        <%= text_field_tag :search, nil, placeholder: 'Search for students', class: 'search__input' %>
        <%= button_tag type: 'submit', class: 'search_button' do %>
          <span class="fa fa-search fa-lg"></span>
        <% end %>
    <% end %>
  </div>

  <div class="logout">
    <%= link_to destroy_user_session_path, class: 'logout__link', method: :delete do %>
      <span class="fa fa-sign-out"></span>
      Sign out
    <% end %>
  </div>

</div>

<div class="sub-header">

  <div class="sub-header-left">
    <%= link_to 'Programs', programs_path, class: 'sub-header-left__link' %>
  </div>

  <div class="sub-header-right">
    <span>Hello, <%= link_to "#{current_user_name}", '#', class: 'sub-header-right__link' %></span>
  </div>

</div>

<div class="container-fluid padding-top-110">
  <%= yield %>
</div>
<%= render 'shared/footer' %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kenshin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/employer_dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kenshin</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<div class="header">

  <div class="logo">
    <%= link_to 'Kenshin', root_path, class: 'logo__link' %>
  </div>

  <div class="logout">
    <%= link_to destroy_user_session_path, class: 'logout__link', method: :delete do %>
        <span class="fa fa-sign-out"></span>
        Sign out
    <% end %>
  </div>

</div>

<div class="container-fluid padding-top-110">
  <%= yield %>
</div>

<%= render 'shared/footer' %>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kenshin</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body class="user-authentication">
<div class="header">
  <div class="logo">
    <%= link_to 'Kenshin', root_path, class: 'logo__link' %>
  </div>
</div>
<div class="message">
  <% flash.each do |type, message| %>
      <%= content_tag :span, message, class: "message__#{type}" %>
  <% end %>
</div>
<%= yield %>
<%= render 'shared/footer' %>
</body>
</html>

app/views/layouts/student_dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kenshin</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<div class="header">

  <div class="logo">
    <%= link_to 'Kenshin', root_path, class: 'logo__link' %>
  </div>

  <div class="navigation-links">
    <%= link_to '#', class: 'header__link' do %>
        <span class="fa fa-home"></span>
        Home
    <% end %>
    <%= link_to '#', class: 'header__link' do %>
        <span class="fa fa-search"></span>
        Job Board
    <% end %>
    <%= link_to '#', class: 'header__link' do %>
        <span class="fa fa-file-text"></span>
        My Application
    <% end %>
    <%= link_to '#', class: 'header__link' do %>
        <span class="fa fa-plane"></span>
        Flight / Visa Information
    <% end %>
    <%= link_to '#', class: 'header__link' do %>
        <span class="fa fa-info-circle"></span>
        SEVIS
    <% end %>
    <%= link_to '#', class: 'header__link' do %>
        <span class="fa fa-wechat"></span>
        Messages
    <% end %>
  </div>

  <div class="logout">
    <%= link_to destroy_user_session_path, class: 'logout__link', method: :delete do %>
        <span class="fa fa-sign-out"></span>
        Sign out
    <% end %>
  </div>

</div>

<div class="sub-header">

  <div class="sub-header-left">
    <%= link_to 'Questionnaire', '#', class: 'sub-header-left__link' %>
    <%= link_to 'Resources', '#', class: 'sub-header-left__link' %>
    <%= link_to 'Help', '#', class: 'sub-header-left__link' %>
    <%= link_to 'F.A.Q.', '#', class: 'sub-header-left__link' %>
  </div>

  <div class="sub-header-right">
    <span class="sub-header-right__span">Season: Work & Travel 2016</span>
    <span>Hello, <%= link_to "#{current_user_name}", '#', class: 'sub-header-right__link' %></span>
  </div>

</div>

<div class="container-fluid padding-top-110">
  <%= yield %>
</div>

<%= render 'shared/footer' %>

</body>
</html>

app/views/shared/_field_errors.html.erb
<% if object.errors[field_name].any? %>
  <ul class="error-messages">
    <% object.errors.full_messages_for(field_name).each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_flash_message.html.erb
<div class="message">
  <% flash.each do |type, message| %>
      <%= content_tag :span, message, class: "message__#{type}" %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="copyright">
    <span class="copyright__text">© 2016, Kenshin</span>
  </div>
  <div class="additional-links">
    <%= link_to 'Home', '#', class: 'additional-links__link' %>
    <%= link_to 'About', '#', class: 'additional-links__link' %>
    <%= link_to 'Program', '#', class: 'additional-links__link' %>
    <%= link_to 'Contact Us', '#', class: 'additional-links__link' %>
  </div>
</div>